article: https://www.bigclown.com/doc/projects/wireless-flood-detector/
images:
  - title:
    url: https://www.bigclown.com/kits/flood-detector/main.png
assembly:
  - name: BigClown Flood Detector
  - name: BigClown Core Module
  - name: BigClown Sensor Module
  - name: BigClown Mini Battery Module
  - name: BigClown Enclosure BCE501
  
