article: https://www.bigclown.com/doc/projects/radio-flood-detector/
images:
  - title:
    url: https://www.bigclown.com/kits/flood-detector/main.png
articles:
  - title: Radio Flood Detector
    url: https://www.hackster.io/jakub-smejkal/radio-flood-detector-a2b67f
    description: Protect your home from the flood with this simple device. It will send you the notification when there is some leak in a bathroom or kitchen
    images:
      - url: https://hackster.imgix.net/uploads/attachments/925597/_Iz5fAtCAQA.blob?auto=compress%2Cformat&w=900&h=675&fit=min
assembly:
  - name: BigClown Flood Detector
  - name: BigClown Core Module
  - name: BigClown Sensor Module
  - name: BigClown Mini Battery Module
  - name: BigClown Enclosure BCE501
